### Signup - Send OTP

POST http://localhost:6000/api/v1/signup
Content-Type: application/json

{
    "username": "nikhilchaughan",
    "email": "nikhilsingh2764@gmail.com",
    "password": "dhn245dfgAA@"
}

###


### Verify OTP

POST http://localhost:6000/api/v1/verify-otp
Content-Type: application/json

{
    "email": "nikhilsingh2764@gmail.com",
    "otp": "676951"
}


### login test 

POST http://localhost:6000/api/v1/Login
Content-Type: application/json

{
    "email": "nikhilsingh2764@gmail.com",
    "password": "Password@123"
}

###

### Get Profile 

GET http://localhost:6000/api/v1/profile 
Cookie: accessToken=    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTY0MDA1NjM2NzM2NmM4OTExODQyMCIsImVtYWlsIjoibmlraGlsc2luZ2gyNzY0QGdtYWlsLmNvbSIsImlhdCI6MTc4NDAzNzM4OCwiZXhwIjoxNzg0MDM4Mjg4fQ.jabUkBuMahF816FaJ8Z7g0bLgAbK89FhO_V45O8I1iU

###

### Refresh Access Token

POST http://localhost:6000/api/v1/refresh-token
Cookie: refreshToken =  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTVlY2MwYWZkZjZjNzNkNTVlM2YxZSIsImlhdCI6MTc4NDAyMDM5OCwiZXhwIjoxNzg1MzE2Mzk4fQ.HnGvr4uZrJ15fzsdQhoRC2W96CHNOZY-C1QyzOhuvMc


### 
### Logout 
POST http://localhost:6000/api/v1/logout 
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTVlY2MwYWZkZjZjNzNkNTVlM2YxZSIsImVtYWlsIjoibmlraGlsc2luZ2gyNzY0QGdtYWlsLmNvbSIsImlhdCI6MTc4NDAyMTE3OSwiZXhwIjoxNzg0MDIyMDc5fQ.g9Q5jWiLpkHdghOW8c5bUMVn4fDH70rhX3xTY98BnC4
        


### Update Profile

PATCH http://localhost:6000/api/v1/Update-Profile
Content-Type: application/json
Cookie: accessToken=  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTYxZDJjMTM4NDk5ODlhYjEwN2MwMyIsImVtYWlsIjoibmlraGlsc2luZ2gyNzY0QGdtYWlsLmNvbSIsImlhdCI6MTc4NDAyOTUyNCwiZXhwIjoxNzg0MDMwNDI0fQ.1u39NY5UwOi1t9_j8tZZM6hQ2l_bcHvBNzRXy5m3-Ms

{
    "username": "vimal"
}


### Change Password

PATCH http://localhost:6000/api/v1/change-password
Content-Type: application/json
Cookie: accessToken=   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTYyOTI4ZTcyZmQxNDBmZjlkNzRjOCIsImVtYWlsIjoibmlraGlsc2luZ2gyNzY0QGdtYWlsLmNvbSIsImlhdCI6MTc4NDAzMTUzNSwiZXhwIjoxNzg0MDMyNDM1fQ.KxHrJNFxySqqJI1fdH87Lzry2LTXfV21ucmg2ano_OI

{
    "oldPassword": "Pass123@AS",
    "newPassword": "dhn245dfgA@"
}


### Deactivate Account

PATCH http://localhost:6000/api/v1/deactivate-account
Cookie: accessToken=  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTYzYzcyMzM0ZjY5ZjZlZDNjY2JjMCIsImVtYWlsIjoibmlraGlsc2luZ2gyNzY0QGdtYWlsLmNvbSIsImlhdCI6MTc4NDAzNjQ3NCwiZXhwIjoxNzg0MDM3Mzc0fQ.gx2XdHWX_211G50_1-TLvbqK_yUvyUDufCZkJQjhR6I


### Delete Account

DELETE http://localhost:6000/api/v1/delete-account
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTY0MDA1NjM2NzM2NmM4OTExODQyMCIsImVtYWlsIjoibmlraGlsc2luZ2gyNzY0QGdtYWlsLmNvbSIsImlhdCI6MTc4NDAzNzM4OCwiZXhwIjoxNzg0MDM4Mjg4fQ.jabUkBuMahF816FaJ8Z7g0bLgAbK89FhO_V45O8I1iU

{
    "password": "dhn245dfgA@"
}



### Forgot Password

POST http://localhost:6000/api/v1/forgot-password
Content-Type: application/json

{
    "email": "nikhilsingh2764@gmail.com"
}


### Reset Password

POST http://localhost:6000/api/v1/reset-password
Content-Type: application/json

{
    "email": "nikhilsingh2764@gmail.com",
    "otp": "135487",
    "newPassword": "Password@123"
}